language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ivk-wordpress' ]; then cd .. && eval "mv $currentfolder generator-ivk-wordpress" && cd generator-ivk-wordpress; fi

